### ISSUE TITLE
Message looks like error, is informational: splicing not possible, trying sendfile

### ISSUE THREAD

**Issue by larswirzenius** [rjek/fling#13]
fling currently tells user that it's using sendfile instead of splice:

```
            fprintf(stdout, "splicing not possible: %s, trying sendfile\n", strerror(errno));
```

To me, that looks an awful lot like an error message. Would you accept a PR to change the message to something like:

```
stdin is a pipe, using splice
stdin is a file, using sendfile
```

Possibly with additional logic to see whether stdin is a pipe or not.

**Comment by rjek** [comment]
The message should only appear when in verbose mode.  Also, while it looks like an error, it is informational: fling attempts the fastest type of transfer first because there's no easy way of finding out what kind of thing the fd you've been given is.  If that fails, it tries the next fastest, and if that fails, plain old copy.  Because of that I wanted to avoid mentioning specific types of fd in the error message.  This "try and see" approach also means that fling will automatically use splice in future if the kernel expands supported fd types.

As such, I wouldn't want to change the logic here, but I am all for alternative wording that may be considered less alarming.

**Comment by larswirzenius** [comment]
Ack on no logic change. How about adding a messge like this just before calling splice:

```
Trying splice on stdin
```

and if that fails:

```
Splice didn't work (stdin not pipe?), trying sendfile instead
```

Alternatively, just the latter one if you don't want a new message.

**Comment by rjek** [comment]
I have pushed a change to make these messages less alarming.  Are these better?

**Comment by larswirzenius** [comment]
Looks good to me.
